import { PARTICIPANT, CURRENCY, CATEGORY, SUBCATE, PARTICIPANT_CH } from './types';

export default [
    {
        payment: 6323,
        payer: PARTICIPANT.YANG,
        currency: CURRENCY.RMB,
        date: '2018-09-27',
        desc: '租车',
        category: CATEGORY.TRAFFIC,
        subCate: SUBCATE.RENTAL,
        participants: PARTICIPANT.ALL,
    },
    {
        payment: 92.43,
        payer: PARTICIPANT.YANG,
        currency: CURRENCY.USD,
        date: '2018-09-27',
        desc: '租车第二驾驶员费用',
        category: CATEGORY.TRAFFIC,
        subCate: SUBCATE.RENTAL,
        participants: PARTICIPANT.ALL,
    },
    {
        payment: 20,
        payer: PARTICIPANT.JIAN,
        currency: CURRENCY.EURO,
        date: '2018-09-27',
        desc: '电话卡充流量',
        category: CATEGORY.OTHERS,
        participants: PARTICIPANT.ALL
    },
    {
        payment: 6,
        payer: PARTICIPANT.CASH,
        currency: CURRENCY.DH,
        date: '2018-09-27',
        desc: '机场高速收费',
        category: CATEGORY.TRAFFIC,
        subCate: SUBCATE.PARKING,
        participants: PARTICIPANT.ALL
    },
    {
        payment: 984,
        payer: PARTICIPANT.CASH,
        currency: CURRENCY.DH,
        date: '2018-09-28',
        desc: 'Le Cuisto Traditionnel本地餐馆',
        category: CATEGORY.DIET,
        subCate: SUBCATE.MOFOOD,
        participants: PARTICIPANT.ALL
    },
    {
        payment: 40,
        payer: PARTICIPANT.CASH,
        currency: CURRENCY.DH,
        date: '2018-09-28',
        desc: '酒店旁停车',
        category: CATEGORY.TRAFFIC,
        subCate: SUBCATE.PARKING,
        participants: PARTICIPANT.ALL,
    },
    {
        payment: 2200,
        payer: PARTICIPANT.PC,
        currency: CURRENCY.DH,
        date: '2018-09-28',
        desc: 'Le Rouget de l\'lsle法国餐厅',
        category: CATEGORY.DIET,
        subCate: SUBCATE.FRFOOD,
        participants: PARTICIPANT.ALL
    },
    {
        payment: 649.78,
        payer: PARTICIPANT.PC,
        currency: CURRENCY.RMB,
        date: '2018-09-28',
        desc: '卡萨酒店住宿',
        category: CATEGORY.HOTEL,
        subCate: SUBCATE.HOTEL,
        participants: PARTICIPANT.ALL
    },
    {
        payment: 60,
        payer: PARTICIPANT.CASH,
        currency: CURRENCY.DH,
        date: '2018-09-28',
        desc: '卡萨酒店的税费',
        category: CATEGORY.HOTEL,
        subCate: SUBCATE.HOTEL,
        participants: PARTICIPANT.ALL, 
    },
    {
        payment: 834,
        payer: PARTICIPANT.CASH,
        currency: CURRENCY.DH,
        date: '2018-09-28',
        desc: 'Restaurant du Port de peche西班牙餐厅',
        category: CATEGORY.DIET,
        subCate: SUBCATE.SPFOOD,
        participants: PARTICIPANT.ALL,
    },
    {
        payment: 20,
        payer: PARTICIPANT.CASH,
        currency: CURRENCY.DH,
        date: '2018-09-28',
        desc: '停车费',
        category: CATEGORY.TRAFFIC,
        subCate: SUBCATE.PARKING,
        participants: PARTICIPANT.ALL,
    },
    {
        payment: 60,
        payer: PARTICIPANT.CASH,
        currency: CURRENCY.DH,
        date: '2018-09-29',
        desc: '停车费',
        category: CATEGORY.TRAFFIC,
        subCate: SUBCATE.PARKING,
        participants: PARTICIPANT.ALL,
    },
    {
        payment: 190,
        payer: PARTICIPANT.CASH,
        currency: CURRENCY.DH,
        date: '2018-09-29',
        desc: '德吉玛广场晚饭',
        category: CATEGORY.DIET,
        subCate: SUBCATE.MOFOOD,
        participants: PARTICIPANT.ALL,
    },
    {
        payment: 1266,
        payer: PARTICIPANT.YANG,
        currency: CURRENCY.DH,
        date: '2018-09-29',
        desc: 'Riad Eden',
        category: CATEGORY.HOTEL,
        subCate: SUBCATE.RIAD,
        participants: PARTICIPANT.ALL
    },
    {
        payment: 1314,
        payer: PARTICIPANT.CASH,
        currency: CURRENCY.DH,
        date: '2018-09-29',
        desc: 'Riad swaka',
        category: CATEGORY.HOTEL,
        subCate: SUBCATE.RIAD,
        participants: PARTICIPANT.ALL,
    },
    {
        payment: 470,
        payer: PARTICIPANT.CASH,
        currency: CURRENCY.DH,
        date: '2018-09-29',
        desc: '油费',
        category: CATEGORY.TRAFFIC,
        subCate: SUBCATE.OIL,
        participants: PARTICIPANT.ALL,
    },
    {
        payment: 350,
        payer: PARTICIPANT.YANG,
        currency: CURRENCY.DH,
        date: '2018-09-30',
        desc: '餐饮费',
        category: CATEGORY.DIET,
        participants: PARTICIPANT.ALL
    },
    {
        payment: 2900,
        payer: PARTICIPANT.YANG,
        currency: CURRENCY.DH,
        date: '2018-09-30',
        desc: '切皮尔斯酒店',
        category: CATEGORY.HOTEL,
        subCate: SUBCATE.RIAD,
        participants: PARTICIPANT.ALL
    },
    {
        payment: 150,
        payer: PARTICIPANT.CASH,
        currency: CURRENCY.DH,
        date: '2018-09-30',
        desc: '加油站午餐',
        category: CATEGORY.DIET,
        subCate: SUBCATE.MOFOOD,
        participants: PARTICIPANT.ALL,
    },
    {
        payment: 3820,
        payer: PARTICIPANT.PC,
        currency: CURRENCY.RMB,
        date: '2018-10-01',
        desc: '阿里与莎拉帐篷',
        category: CATEGORY.HOTEL,
        subCate: SUBCATE.TENT,
        participants: PARTICIPANT.ALL,
    },
    {
        payment: 318,
        payer: PARTICIPANT.YANG,
        currency: CURRENCY.RMB,
        date: '2018-10-01',
        desc: '北京饭店中餐',
        category: CATEGORY.DIET,
        subCate: SUBCATE.CHFOOD,
        participants: PARTICIPANT.ALL,
    },
    {
        payment: 720,
        payer: PARTICIPANT.CASH,
        currency: CURRENCY.DH,
        date: '2018-10-02',
        desc: '菲斯午餐',
        category: CATEGORY.DIET,
        subCate: SUBCATE.MOFOOD,
        participants: PARTICIPANT.ALL,
    },
    {
        payment: 400,
        payer: PARTICIPANT.CASH,
        currency: CURRENCY.DH,
        date: '2018-10-02',
        desc: '菲斯导游费',
        category: CATEGORY.OTHERS,
        participants: PARTICIPANT.ALL
    },
    {
        payment: 60,
        payer: PARTICIPANT.CASH,
        currency: CURRENCY.DH,
        date: '2018-10-03',
        desc: '停车费',
        category: CATEGORY.TRAFFIC,
        subCate: SUBCATE.PARKING,
        participants: PARTICIPANT.ALL,
    },
    {
        payment: 20,
        payer: PARTICIPANT.CASH,
        currency: CURRENCY.DH,
        date: '2018-10-03',
        desc: '电话卡充值通话时间',
        category: CATEGORY.OTHERS,
        participants: PARTICIPANT.ALL
    },
    {
        payment: 50,
        payer: PARTICIPANT.CASH,
        currency: CURRENCY.DH,
        date: '2018-10-03',
        desc: '给菲斯酒店小哥的小费',
        category: CATEGORY.OTHERS,
        subCate: SUBCATE.TIP,
        participants: PARTICIPANT.ALL
    },
    {
        payment: 30,
        payer: PARTICIPANT.CASH,
        currency: CURRENCY.DH,
        date: '2018-10-03',
        desc: '搬行李的小费',
        category: CATEGORY.OTHERS,
        subCate: SUBCATE.TIP,
        participants: PARTICIPANT.ALL
    },
    {
        payment: 255,
        payer: PARTICIPANT.PC,
        currency: CURRENCY.RMB,
        date: '2018-10-04',
        desc: '天空之城中餐',
        category: CATEGORY.DIET,
        subCate: SUBCATE.CHFOOD,
        participants: [PARTICIPANT.YANG,PARTICIPANT.JIAN,PARTICIPANT.PC]
    },
    {
        payment: 255,
        payer: PARTICIPANT.MAY,
        currency: CURRENCY.RMB,
        date: '2018-10-04',
        desc: '天空之城二刷，价格都一样的好神奇',
        category: CATEGORY.DIET,
        subCate: SUBCATE.CHFOOD,
        participants: PARTICIPANT.ALL
    },
    {
        payment: 60,
        payer: PARTICIPANT.CASH,
        currency: CURRENCY.DH,
        date: '2018-10-04',
        desc: '搬行李的小费',
        category: CATEGORY.OTHERS,
        subCate: SUBCATE.TIP,
        participants: PARTICIPANT.ALL
    },
    {
        payment: 40,
        payer: PARTICIPANT.CASH,
        currency: CURRENCY.DH,
        desc: '停车费',
        date: '2018-10-04',
        category: CATEGORY.TRAFFIC,
        subCate: SUBCATE.PARKING,
        participants: PARTICIPANT.ALL,
    },
    {
        payment: 1374,
        payer: PARTICIPANT.PC,
        currency: CURRENCY.DH,
        desc: '舍夫沙万酒店',
        date: '2018-10-04',
        category: CATEGORY.HOTEL,
        subCate: SUBCATE.RIAD,
        participants: PARTICIPANT.ALL
    },
    {
        payment: 620,
        payer: PARTICIPANT.CASH,
        currency: CURRENCY.DH,
        desc: '油费',
        date: '2018-10-04',
        category: CATEGORY.TRAFFIC,
        subCate: SUBCATE.OIL,
        participants: PARTICIPANT.ALL
    },
    {
        payment: 40,
        payer: PARTICIPANT.CASH,
        currency: CURRENCY.DH,
        desc: '打车去中餐馆',
        date: '2018-10-05',
        category: CATEGORY.TRAFFIC,
        subCate: SUBCATE.TAXI,
        participants: PARTICIPANT.ALL,
    },
    {
        payment: 14,
        payer: PARTICIPANT.CASH,
        currency: CURRENCY.DH,
        desc: '打车回酒店',
        date: '2018-10-05',
        category: CATEGORY.TRAFFIC,
        subCate: SUBCATE.TAXI,
        participants: [PARTICIPANT.YANG, PARTICIPANT.JIAN, PARTICIPANT.MAY]
    },
    {
        payment: 313,
        payer: PARTICIPANT.YANG,
        currency: CURRENCY.RMB,
        desc: '安吉中餐馆',
        date: '2018-10-05',
        category: CATEGORY.DIET,
        subCate: SUBCATE.CHFOOD,
        participants: [PARTICIPANT.YANG, PARTICIPANT.JIAN, PARTICIPANT.PC]
    },
    {
        payment: 36,
        payer: PARTICIPANT.CASH,
        currency: CURRENCY.DH,
        desc: '超市',
        date: '2018-10-05',
        category: CATEGORY.OTHERS,
        participants: [PARTICIPANT.YANG]
    },
    {
        payment: 2800,
        payer: PARTICIPANT.YANG,
        currency: CURRENCY.DH,
        desc: 'Grand Hotel丹吉尔',
        date: '2018-10-05',
        category: CATEGORY.HOTEL,
        subCate: SUBCATE.HOTEL,
        participants: PARTICIPANT.ALL,
    },
    {
        payment: 80,
        payer: PARTICIPANT.CASH,
        currency: CURRENCY.DH,
        desc: '打车去斯帕特尔角的公园',
        date: '2018-10-05',
        category: CATEGORY.TRAFFIC,
        subCate: SUBCATE.TAXI,
        participants: PARTICIPANT.ALL
    },
    {
        payment: 100,
        payer: PARTICIPANT.CASH,
        currency: CURRENCY.DH,
        desc: '打车回酒店',
        date: '2018-10-05',
        category: CATEGORY.TRAFFIC,
        subCate: SUBCATE.TAXI,
        participants: PARTICIPANT.ALL,
    },
    {
        payment: 1165,
        payer: PARTICIPANT.PC,
        currency: CURRENCY.DH,
        desc: '艾西拉酒店',
        date: '2018-10-06',
        category: CATEGORY.HOTEL,
        subCate: SUBCATE.AP,
        participants: PARTICIPANT.ALL
    },
    {
        payment: 265,
        payer: PARTICIPANT.CASH,
        currency: CURRENCY.DH,
        desc: '艾西拉换海景房的费用',
        date: '2018-10-06',
        category: CATEGORY.HOTEL,
        subCate: SUBCATE.AP,
        participants: PARTICIPANT.ALL
    },
    {
        payment: 410,
        payer: PARTICIPANT.CASH,
        currency: CURRENCY.DH,
        desc: '艾西拉酒店晚餐',
        date: '2018-10-06',
        category: CATEGORY.DIET,
        subCate: SUBCATE.WEFOOD,
        participants: [PARTICIPANT.YANG, PARTICIPANT.JIAN, PARTICIPANT.PC],
    },
    {
        payment: 300,
        payer: PARTICIPANT.CASH,
        currency: CURRENCY.DH,
        desc: '艾西拉酒店早餐',
        date: '2018-10-06',
        category: CATEGORY.DIET,
        subCate: SUBCATE.MOFOOD,
        participants: [PARTICIPANT.YANG, PARTICIPANT.JIAN, PARTICIPANT.PC],
    },
    {
        payment: 526,
        payer: PARTICIPANT.CASH,
        currency: CURRENCY.DH,
        desc: '卡萨金华中餐馆',
        date: '2018-10-06',
        category: CATEGORY.DIET,
        subCate: SUBCATE.CHFOOD,
        participants: PARTICIPANT.ALL,
    },
    {
        payment: 391,
        payer: PARTICIPANT.CASH,
        currency: CURRENCY.DH,
        desc: '油费',
        date: '2018-10-07',
        category: CATEGORY.TRAFFIC,
        subCate: SUBCATE.OIL,
        participants: PARTICIPANT.ALL,
    },
    {
        payment: 1100,
        payer: PARTICIPANT.CASH,
        currency: CURRENCY.DH,
        desc: '卡萨酒店part 1',
        date: '2018-10-07',
        category: CATEGORY.HOTEL,
        subCate: SUBCATE.HOTEL,
        participants: PARTICIPANT.ALL,
    },
    {
        payment: 895,
        payer: PARTICIPANT.PC,
        currency: CURRENCY.DH,
        desc: '卡萨酒店part 2',
        date: '2018-10-07',
        category: CATEGORY.HOTEL,
        subCate: SUBCATE.HOTEL,
        participants: PARTICIPANT.ALL,
    },
    {
        payment: 10,
        payer: PARTICIPANT.CASH,
        currency: CURRENCY.DH,
        desc: '机场停车费',
        date: '2018-10-07',
        category: CATEGORY.TRAFFIC,
        subCate: SUBCATE.PARKING,
        participants: PARTICIPANT.ALL,
    },
    {
        payment: 270,
        payer: PARTICIPANT.PC,
        currency: CURRENCY.RMB,
        desc: '金华餐厅外卖',
        date: '2018-10-07',
        category: CATEGORY.DIET,
        subCate: SUBCATE.CHFOOD,
        participants: [PARTICIPANT.YANG, PARTICIPANT.JIAN, PARTICIPANT.PC]
    },
    {
        payment: 205,
        payer: PARTICIPANT.CASH,
        currency: CURRENCY.DH,
        desc: '唇膏，冰箱贴，石头，冰淇淋',
        category: CATEGORY.OTHERS,
        participants: [PARTICIPANT.MAY]
    },
    {
        payment: 500,
        payer: PARTICIPANT.CASH,
        currency: CURRENCY.DH,
        desc: '头巾，水果，擦脸的',
        category: CATEGORY.OTHERS,
        participants: [PARTICIPANT.YANG]
    },
    {
        payment: 40,
        payer: PARTICIPANT.CASH,
        currency: CURRENCY.DH,
        desc: '小费',
        category: CATEGORY.OTHERS,
        subCate: SUBCATE.TIP,
        participants: PARTICIPANT.ALL
    },
    {
        payment: 20,
        payer: PARTICIPANT.CASH,
        currency: CURRENCY.DH,
        desc: '打车',
        category: CATEGORY.TRAFFIC,
        subCate: SUBCATE.TAXI,
        participants: PARTICIPANT.ALL,
    },
    {
        payment: 30,
        payer: PARTICIPANT.CASH,
        currency: CURRENCY.DH,
        desc: '橙汁菲斯',
        category: CATEGORY.OTHERS,
        participants: [PARTICIPANT.JIAN, PARTICIPANT.MAY],
    },
    {
        payment: 350,
        payer: PARTICIPANT.CASH,
        currency: CURRENCY.DH,
        desc: '感谢超妹儿同事的精油',
        category: CATEGORY.OTHERS,
        participants: PARTICIPANT.ALL,
    },
    {
        payment: 235,
        payer: PARTICIPANT.CASH,
        currency: CURRENCY.DH,
        desc: '围巾，纪念品，早餐蛋糕，马拉喀什香包，菲斯下午茶',
        category: CATEGORY.OTHERS,
        participants: [PARTICIPANT.PC]
    }
]